name: Tests

on:
  pull_request:
    branches: 
    - 'release'
    - 'develop'
    - 'releases/**'
    - 'blockchains/**'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_IOS }}

jobs:
  test:
    name: Test
    runs-on: macos-14
    steps:
    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'
    - name: Checkout
      uses: actions/checkout@v2   
    - name: Bundle Install
      run: bundle install
    - name: Tests
      run: bundle exec fastlane test
